# Generated by Django 2.2.7 on 2019-12-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holding', '0002_holding_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=60)),
                ('date', models.DateTimeField()),
                ('askprice', models.DecimalField(decimal_places=2, max_digits=11)),
                ('bidprice', models.DecimalField(decimal_places=2, max_digits=11)),
                ('highprice', models.DecimalField(decimal_places=2, max_digits=11)),
                ('lowprice', models.DecimalField(decimal_places=2, max_digits=11)),
                ('updated', models.DateTimeField()),
            ],
        ),
    ]
