# Generated by Django 2.2.7 on 2019-12-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holding', '0005_auto_20191205_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtime',
            name='lastprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
