# Generated by Django 2.2.7 on 2019-12-06 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_portfolio_content'),
        ('holding', '0006_realtime_lastprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Portfolio'),
        ),
    ]
