# Generated by Django 2.2.7 on 2019-12-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holding', '0008_holding_hnamef'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtime',
            name='lastpricep',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
