# Generated by Django 2.2.7 on 2019-12-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holding', '0011_auto_20191210_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holding',
            old_name='updownh',
            new_name='updownhp',
        ),
        migrations.AddField(
            model_name='holding',
            name='updownhv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
    ]
