# Generated by Django 2.2.7 on 2019-12-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holding', '0012_auto_20191210_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtime',
            name='updownrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtime',
            name='updownrv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
