# Generated by Django 2.2.7 on 2019-12-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holding', '0013_auto_20191210_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtime',
            name='name',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
