# Generated by Django 2.2.7 on 2019-12-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holding', '0014_realtime_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtime',
            name='date',
            field=models.DateField(max_length=60),
        ),
    ]
