# Generated by Django 2.2.7 on 2019-12-11 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holding', '0019_reminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='reminder',
            new_name='v',
        ),
    ]
