# Generated by Django 2.2.7 on 2019-12-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holding', '0021_auto_20191211_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='value',
            new_name='valueDown',
        ),
        migrations.AddField(
            model_name='reminder',
            name='valueUp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
