# Generated by Django 2.2.7 on 2019-12-12 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_watchlist'),
        ('holding', '0022_auto_20191211_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchHolding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whnamef', models.CharField(max_length=60)),
                ('whname', models.CharField(max_length=60)),
                ('whvalue', models.DecimalField(decimal_places=2, max_digits=11)),
                ('whvaluep', models.DecimalField(decimal_places=2, max_digits=11)),
                ('wupdownhp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wupdownhv', models.DecimalField(decimal_places=2, max_digits=11)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.WatchList')),
            ],
        ),
    ]
