# Generated by Django 2.2.7 on 2019-12-02 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('holding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.DecimalField(decimal_places=2, max_digits=11)),
                ('pname', models.CharField(max_length=60)),
                ('pvalue', models.DecimalField(decimal_places=2, max_digits=11)),
                ('pvaluep', models.DecimalField(decimal_places=2, max_digits=11)),
                ('holding', models.ManyToManyField(to='holding.Holding')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
