# Generated by Django 2.2.7 on 2019-12-05 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holding', '0002_holding_user'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='holding',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='holding',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='holding.Holding'),
            preserve_default=False,
        ),
    ]
