# Generated by Django 2.2.7 on 2019-12-06 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20191206_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='holding.Holding'),
        ),
    ]
