# Generated by Django 2.2.7 on 2019-12-06 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20191206_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='content',
        ),
    ]
