# Generated by Django 2.2.7 on 2019-12-10 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20191210_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='downp',
            new_name='updownp',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='upp',
        ),
    ]
