# Generated by Django 2.2.7 on 2019-12-12 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20191210_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='pvalue1',
            new_name='updownpp1',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='pvalue2',
            new_name='updownpp2',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='pvalue3',
            new_name='updownpp3',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='pvalue4',
            new_name='updownpp4',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='pvalue5',
            new_name='updownpp5',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='pvalue6',
            new_name='updownpp6',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='pvalue7',
            new_name='updownpp7',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='pvalue8',
            new_name='updownpp8',
        ),
    ]
