# Generated by Django 2.2.7 on 2019-12-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holding', '0024_auto_20191216_1057'),
        ('portfolio', '0015_watchlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
